import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { homePath, loginPath, ticketsPath } from "@/path";
import { Button, buttonVariants } from "@/components/ui/button";
import { LucideKanban } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav
          className="
          supports-backdrop-blur:bg-background/60
          fixed left-0 right-0 top-0 z-20
          border-b bg-baackground/95 backdrop-blur
          w-full flex justify-between py-2.5 px-5"
        >
          <div className="flex gap-2">
            <div>
              <Button asChild variant="outline">
                <Link href={homePath}>
                  <LucideKanban />
                  <h1 className="text-lg font-semibold">TicketBounty</h1>
                </Link>
              </Button>
            </div>
            <div>
              <Link
                href={ticketsPath}
                className={buttonVariants({ variant: "outline" })}
              >
                Tickets
              </Link>
            </div>
          </div>
          <div className="flex gap-2">
            <div>
              <Link
                href={loginPath}
                className={buttonVariants({ variant: "outline" })}
              >
                Login
              </Link>
            </div>
          </div>
        </nav>
        <main
          className="
          main-h-screen flex-1
          overflow-y-auto overflow-x-auto
          py-20 px-8
          bg-secondaary/20
          flex flex-col"
        >
          {children}
        </main>
      </body>
    </html>
  );
}
